# example config for BME280 temperature and pressure sensor

DAQModule: BME280Config
# I2CADDR: 0x76 # 0x77 is default, 0x76 alternative
# SeaLevelPressure: 1013.25
# NChannels: 2 # Description 1 (temperature), 2 (temperature, pressure), 3 (temperature, pressure, altitude),
#              # 4 (temperature, pressure, altitude, relative_humidity)