# example of a configuration file for HX711

DAQModule: HX711Config

DT: 5                   # chosen DT-GPIO
SCK: 6                  # chosen SCK-GPIO
Gain: 128               # programmable gain:
                          # possible values for Gain:
                            # 128 (use Channel A!)
                            #  64 (use Channel A!)
                            #  32 (use Channel B!)
